

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  evm:
    name: Vanilla Foundry (ERC4337 / EVM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Cache Foundry
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            cache
            out
          key: ${{ runner.os }}-foundry-${{ hashFiles('foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Show Forge Version
        run: forge --version

      - name: Format Check
        run: forge fmt --check

      - name: Build
        run: forge build --sizes

      - name: Run EVM Tests
        run: forge test --match-path "test/ETHAA/*" -vvv

  
  zksync:
    name: zkSync Foundry (Native AA)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - name: Clone zkSync Foundry
        run: git clone https://github.com/matter-labs/foundry-zksync.git

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            foundry-zksync/target
          key: ${{ runner.os }}-cargo-zksync-${{ hashFiles('foundry-zksync/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-zksync-

      - name: Build zkSync Forge Only
        run: |
          cd foundry-zksync
          cargo build --release -p forge
          echo "$PWD/target/release" >> $GITHUB_PATH

      - name: Run zkSync Tests
        run: forge test --match-path "test/ZKAA/*" --zksync -vvv --no-match-test testZKfunctionValidateTransaction

      - name: Run System Mode Test
        run: forge test --mt testZKfunctionValidateTransaction --zksync --system-mode=true -vvv