name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  evm:
    name: Vanilla Foundry (ERC4337 / EVM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Cache Foundry
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            cache
            out
          key: ${{ runner.os }}-foundry-${{ hashFiles('foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Show Forge Version
        run: forge --version

      - name: Format Check
        run: forge fmt --check

      - name: Build
        run: forge build --sizes

      - name: Run EVM Tests
        run: forge test --match-path "test/ETHAA/*" -vvv



  zksync:
    name: zkSync Foundry (Native AA)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install zkSync Foundry
        uses: matter-labs/foundry-zksync-action@v1

      - name: Cache zkSync Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            cache-zk
            out-zk
          key: ${{ runner.os }}-zksync-${{ hashFiles('foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-zksync-

      - name: Show Forge Version
        run: forge --version

      - name: Run zkSync Tests
        run: forge test --match-path "test/ZKAA/*" -vvv